### ISSUE TITLE
feature: multi user support and access control based on RBAC

### ISSUE THREAD

**Issue by nitisht** [parseablehq/parseable#250]
This includes following items

- [x] Multi user support --> Done with PR #409 
- [x] Authorisation mechanism based on roles setting per user --> Done with PR #417 
- [x] Integration tests in Quest --> PR https://github.com/parseablehq/quest/pull/21
- [x] Documentation
- [x] High CPU usage in hashing. Need to change to another hashing approach. --> #425 
- [x] List user roles API --> `GET {{endpoint}}/api/v1/user/{{username}}/role` --> #425 
- [x] Label based access for reader privilege --> #429

**Comment by nitisht** [comment]
Feature is complete now.
